trigger:

- main
 
pool:

  vmImage: ubuntu-latest
 
strategy:

  matrix:

    Python36:

      python.version: '3.6'

    Python37:

      python.version: '3.7'

    Python38:

      python.version: '3.8'

    Python39:

      python.version: '3.9'

    Python310:

      python.version: '3.10'
 
steps:

- task: UsePythonVersion@0

  inputs:

    versionSpec: '$(python.version)'

    addToPath: true

  displayName: 'Use Python $(python.version)'
 
- script: |

    python -m pip install --upgrade pip

    pip --version

    python --version

    pip install -r requirements.txt

  displayName: 'Install dependencies'

  continueOnError: true
 
- script: |

    pip install pytest pytest-azurepipelines

    pytest

  displayName: 'Run tests with pytest'

  continueOnError: true
 
- script: |

    python setup.py sdist bdist_wheel

    twine upload --repository-url https://test.pypi.org/legacy/ -u $(twine_username) -p $(twine_password) dist/*

  displayName: 'Build and publish package'

  env:

    TWINE_USERNAME: $(twine_username)

    TWINE_PASSWORD: $(twine_password)

  continueOnError: true
 
- task: PublishBuildArtifacts@1

  inputs:

    pathToPublish: 'dist'

    artifactName: 'python_package'

  displayName: 'Publish Build Artifacts'

  continueOnError: true

